class StorageAlreadyExistsError(Exception):
    pass


class StorageNotFoundError(Exception):
    pass
